### ISSUE TITLE
Flexible search

### ISSUE THREAD

**Issue by c-martinez** [CrowdTruth/CrowdTruth#11]
Different view is required to visualize entities of a particular document type. Each view must be specifically coded for the particular document type. E.g: one view exists for RelEx type documents, another exists for Videos, etc.

A flexible document view is required. This view sill include capability to search on specific criteria, for example: "show all documents" of medical domain will show not only RelEx files, but also other documents in this domain (csv, images, etc). Columns which are not available for a given entity will simply be left blank for that entity.

**Comment by Bouncer** [comment]
Views are now project and document type independent
