### ISSUE TITLE
Validate entities created in bulk

### ISSUE THREAD

**Issue by c-martinez** [CrowdTruth/CrowdTruth#38]
Issue #37 suggests validating entities when they are created. This works when a new entity is created:

```
$e = new Entity();
...
$e->save();
```

But will break when entities are created in bulk:

```
$fullEntities = [];
foreach (...) {
  // Collect data for the entity in an array called $fullEntity
  ...
  array_push($fullEntities, $fullEntity);
}
\DB::collection('entities')->insert($fullEntities);
```

This is the case for example in *app/softwareComponents/TextSentencePreprocessor.php* and *app/models/preprocess/RelexStructurer.php*, and we should find a way to work around it.

**Comment by Bouncer** [comment]
Solved in models
