### ISSUE TITLE
no results from rijksmuseum imagegetter

### ISSUE THREAD

**Issue by cwmeijer** [CrowdTruth/CrowdTruth#41]
After installing Crowd Truth using Vagrant I tried adding some data from online sources. When I try to use the Rijksmuseum image getter to get images of dogs, a request is done to 
http://localhost:8888/api/actions/image/art/drawing/16/hond
This request returns:
"[]"
In fact I could not find a query from the image getter that did give me any results.

The other online source, Sound and Vision, also doesn't seem to work, so maybe the problem is more general.

**Comment by c-martinez** [comment]
Looks like it was a firewall issue, right?
