### ISSUE TITLE
Vagrant image installation scripts contain errors

### ISSUE THREAD

**Issue by cwmeijer** [CrowdTruth/CrowdTruth#42]
The installations scripts for the non-public Vagrant images contain some errors that break functionality completely. Here are the changes that need to me done:

vagrant_crowdtruth_june/install.sh:
r26 
xsudo apt-get install -y nginx php5-fpm php5-cli php5-curl php5-mcrypt php-pear php5-dev git mongodb-10gen samba ffmpeg
-> 
sudo apt-get install -y nginx php5-fpm php5-cli php5-curl php5-mcrypt php-pear php5-dev git mongodb-10gen samba ffmpeg

r63 
sudo git clone -b dev https://github.com/laroyo/CrowdTruth.git .
->
sudo git clone -b dev https://github.com/CrowdTruth/CrowdTruth.git .

And I also checked the Watson project:
vagrant_crowdwatson_april9/install.sh:
r63
sudo git clone https://github.com/laroyo/CrowdTruth.git .
->
sudo git clone https://github.com/CrowdTruth/CrowdTruth.git .

**Comment by Bouncer** [comment]
Changes are done.
