### ISSUE TITLE
Database initialization and Uploading Media: Images and Videos

### ISSUE THREAD

**Issue by mjunyent** [CrowdTruth/CrowdTruth#43]
Hello,

I'm trying to install and use CrowdTruth in my server and I'm facing several problems.

First of all Wiki is a bit outdated since last stable release. First problem I had was how to create an authorised user. I think database initialisation command with explanation should be added: 
```
php artisan db:seed --class=DatabaseSeeder
```

Uploading text documents works well but I'm having errors reported when trying to upload images or videos. I've been trying to track them and they all come from app/softwareComponents/FileUploader.php

First of all, validation rules use the keys 'images' and 'videos'
```
	protected $validationRules = [
			'text' => ['file' => 'mimes:txt|max:900000'],
			'images' => ['file' => 'mimes:png|jpg|max:2000'],
			'videos' => ['file' => 'mimes:mp4|avi|max:2000']
	];
	
	protected $extraAllowedMimeTypes = [
			'text' => [
					'text/plain',
					'text/anytext',
					'application/txt',
					'application/octet-stream',
					'text/x-c',
					'text/x-asm',
					'text/x-pascal',
					'text/x-c++',
					'text/html'
			],
			'images' => [
					'text/plain' // To be added
			],
			'videos' => [
					'text/plain' // To be added
			]
	];
```

But getType returns keys 'image' and 'video'
```
			case 'file_format_text':
				return 'text';
			case 'file_format_image':
				return 'image';
			case 'file_format_video':
				return 'video';
```

Because of this performValidation function throws an error.

I changed the key names to fix it but then i got another error from the validator. Validation rules are wrong:

```
			'images' => ['file' => 'mimes:png|jpg|max:2000'],
			'videos' => ['file' => 'mimes:mp4|avi|max:2000']
```

Should be

```
			'images' => ['file' => 'mimes:png,jpg|max:2000'],
			'videos' => ['file' => 'mimes:mp4,avi|max:2000']
```

or
```
			'images' => ['file' => 'image|max:2000'],
```
Otherwise Validator tries to look for an avi and a jpg rules that don't exist.

After solving this I still get another error about non-utf8 content that comes from line 129 when saving the entity, I suppose that this is because raw file is being added as content in line 126.

Is video and audio media upload implemented and supported?

Also getting images from both the online sources doesn't seem to work. I checked that the python scripts can run properly and also, Rijksmuseum image getter worked well with February stable release.

Lastly, in the media tab i get an endless loading page, with empty select columns form. I didn't found why this happens.

Am I missing some install steps? There is more documentation than the wiki?

Thanks

Marc

**Comment by c-martinez** [comment]
Hi Marc,

I think you are right in saying the wiki is probably not completely up to date. If there are more things you notice, please feel free to update it as required.

As for file uploads, I think the issue here is that you are trying to upload the content (in this case the images) directly, while normally you should have a URL to the image/video you are using. That is how the image entities for Dr. Detective are created, and I think it is also the case for Benjamin's sounds and Oana's videos.

Like you rightly point, in this way we don't need to save the image as part of the entity. It may be possible to save the binary image as an attribute in the entity (i.e. content), but I think you might need to change the file uploader a bit to do this.

Cheers,
Carlos

**Comment by mjunyent** [comment]
Hi,

Thanks a lot, I read about the csv but when I started debugging I forgot. This makes a lot more sense.

Anyways the changes to the validation rules keys are still necessary, don't they? Also the validation rules shouldn't need to specify for jpg, avi... mime types?

Any hints on the other errors? I can't see my uploaded media, the loading circle keeps spinning and I have a javascript error:
```
 [Error] TypeError: null is not an object (evaluating 'columns.length')
	dynamicTemplate (search, line 3433)
	(anonymous function) (search, line 3322)
	c (application.js, line 3)
	fireWith (application.js, line 3)
	k (application.js, line 5)
	r (application.js, line 5)
```

Thanks again,
Marc

**Comment by c-martinez** [comment]
Yes I think changes in validation rules wouldn't hurt.

Glad you figured out the search index on your own.
