### ISSUE TITLE
Clicking upload media without required software component exception message

### ISSUE THREAD

**Issue by cwmeijer** [CrowdTruth/CrowdTruth#44]
When I click upload media from the main page as a logged in user, I expect to see the upload screen. Because I didn't seed the database yet with software components, it couldn't find it and gave me this error:
![image](https://cloud.githubusercontent.com/assets/6087314/8669992/4b5d3fb6-2a19-11e5-80ee-0f94be27432d.png)
It would be nice if this was handled better: a clearer error message stating what could be the actual problem or maybe even a link to the documentation about adding software components.

**Comment by Bouncer** [comment]
Solved by auto seeding the database on install.
