### ISSUE TITLE
Error uploading media 

### ISSUE THREAD

**Issue by cyberandy** [CrowdTruth/CrowdTruth#48]
While trying to upload a CSV with a list of images I have noticed that there are no projects in the _Upload to project_ field. As soon as I start the upload I receive the following error: "You do not have permission to perform selected action". My user is *Admin*. 

Is there something we're missing in our installation? What is needed to have groups and projects configured in our instance? Is the upload error somehow related to this misconfiguration? 

Many thanks

**Comment by Bouncer** [comment]
It might be that the permissions were not added in the database. Please run:
```
php artisan db:seed --class=PermissionSeeder
```
And verify whether you can see the project on `/projects`

**Comment by ziodave** [comment]
Yep, this is working now.
