### ISSUE TITLE
Format not set when creating a new batch

### ISSUE THREAD

**Issue by Jorann** [CrowdTruth/CrowdTruth#49]
When you create a new job (beta), the template dropdown is empty. This is because it selects suitable templates based on the 'format'-field of the batch entry in mongo. This is not set when creating a batch, leaving the template dropdown empty.

**Comment by Jorann** [comment]
app/models/Entities/Batch.php was edited in 963399e71be757899f1cf6eb30c55df2ec534a1c
the format field was removed

**Comment by Jorann** [comment]
Fixed it now by editing the MongoDB and adding format: text into the batch entity

**Comment by Bouncer** [comment]
There should not be a format or a domain in a batch, that was part of the old data model.
