### ISSUE TITLE
Preprocessing results in error

### ISSUE THREAD

**Issue by MerelvanEmpel** [CrowdTruth/CrowdTruth#64]
Recreation steps: 
1. Upload a .csv with url's
2. Go to Preprocess Media
3. click on your .csv
4. Document Type: "images"
5. In structure put "url"
6. click the Property button
7. click Save Content

Laravel error: Call to undefined method Jenssegers\Mongodb\Query\Builder::store()
stack origin: CrowdTruth\app\models\Entities\Unit.php 
line 40: SoftwareAgent::store('filecreator', 'Unit creation');

**Comment by oana-inel** [comment]
In the latest version this error is not present. 
There is no call to a store() function.
