### ISSUE TITLE
Not able to make jobs with more then 100 units

### ISSUE THREAD

**Issue by MerelvanEmpel** [CrowdTruth/CrowdTruth#65]
I uploaded a document with more then 100 sentences to CrowdTruth and I want to make a job with all of the sentences. I cannot display them all at once in the "media" page of CT and thus I cannot select them all to create a new job. 

Please make it so I can do this with documents with more then 100 sentences.

**Comment by Jorann** [comment]
Add <option value="99999999999">All Records</option> to line 156 in app/views/media/search/pages/media.blade.php ?

Or fix this nicely?

**Comment by Bouncer** [comment]
This was fixed for now in 2f68fb9db4251a7ea6de5caff96e1c00ecfd51aa
