### ISSUE TITLE
Error when trying to create a new Batch

### ISSUE THREAD

**Issue by MerelvanEmpel** [CrowdTruth/CrowdTruth#66]
When I try to create a new Batch I get the error: 
BadMethodCallException
Call to undefined method Jenssegers\Mongodb\Query\Builder::store()

Last code that belongs to us on the error stack is: 
C:\wamp\www\CrowdTruth\app\models\Entities\Batch.php
line 31: SoftwareAgent::store('batchcreator', 'Batch creation');

Let me know if you need any additional information

**Comment by Jorann** [comment]
Attempted fix successful in 3080e1caa3689a10fe2a1e439cb5e60c889ed65d
