### ISSUE TITLE
Error when accessing CT

### ISSUE THREAD

**Issue by Jorann** [CrowdTruth/CrowdTruth#72]
Call to undefined method Security\ProjectHandler::listGroups()

in: /var/www/CrowdTruth/app/controllers/PagesController.php
Line 10.

ProjectHandler class does not have the listGroups method. Are you still working on this?
I pulled the latest dev branch from github.

**Comment by Bouncer** [comment]
Groups changed to projects, so just rename the call in the pages controller
to listprojects

**Comment by Jorann** [comment]
Thanks, fixed.
