### ISSUE TITLE
Get data from Dive Dashboard and save it in CrowdTruth database

### ISSUE THREAD

**Issue by oana-inel** [CrowdTruth/CrowdTruth#73]
In V1.0. we want to save the data received from Dive Dashboard into units. 
No batches will be created now. For this, we go to CrowdTruth.

- create a generic user to communicate with Dive Dashboard
- the POST request from Dive Dashboard should contain:
  - a user
  - a project for the data to be stored
  - the source of the objects
  - a description of the data
  - the document type 
  - an array of objects that need to contain an ID -> identity in the triplestore

- CrowdTruth should send back for each object:
  - a mapping of (triplestore ID - CT ID)
  - a status: added/existing/error

**Comment by c-martinez** [comment]
@oana-inel -- just a random thought, do you think we should include a `source` parameter? So we know that entities with `source=dive` come from the Dive dashboard, and entities with `source=drdetective` (for instance) come from a different source? In that way, if we want to add more clients which use the API in the future, we could. What do you think?
